language: node_js
notifications:
  email: false
branches:
  except:
  - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+(@(alpha|beta))?)?$/
deploy:
  provider: script
  edge: true
  script: npx semantic-release
  on:
    all_branches: true
env:
  global:
    - FORCE_COLOR=1
    - NPM_CONFIG_COLOR=always
